package com.Farm360.utils;

public enum NotificationType {

    AGREEMENT_CREATED,
    SUPPLY_REQUESTED,
    SUPPLIER_ACCEPTED,
    MATERIAL_DISPATCHED,
    DELIVERY_CONFIRMED,
    DELIVERY_REJECTED,
    BUYER_APPROVED,
    PAYMENT_RELEASED,
    FARMER_PAID,
    AGREEMENT_COMPLETED,
    REQUEST_RECEIVED, REQUEST_ACCEPTED, REQUEST_REJECTED, PROPOSAL_RECEIVED, PROPOSAL_ACCEPTED, PROPOSAL_FINAL_ACCEPTED, PROPOSAL_REJECTED, COUNTER_PROPOSAL_RECEIVED, PROPOSAL_EXPIRED, SUPPLIER_PAYMENT_RELEASED, ESCROW_DEBITED, ESCROW_REFUNDED, FARMER_PAYMENT_RECEIVED, SUPPLY_REQUEST, SUPPLY_DISPATCHED, FARMER_CONFIRMED_SUPPLY, SUPPLY_REJECTED, SUPPLY_REQUEST_CREATED, SUPPLIER_BILL_UPLOADED, SUPPLY_FAILED, SUPPLY_APPROVED, SYSTEM_ALERT
}
